name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        sdk: 10.0.18362.0
        toolset: 19.XX
    - name: compile
      run: | 
        cl cve-2024-21338.c /Fe:cve-2024-21338 /std:c++latest
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          cve-2024-21338.exe
